create table if not exists public.post_views (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  ip_address text not null,
  created_at timestamptz not null default now(),
  unique (post_id, ip_address)
);

create index if not exists post_views_post_id_idx on public.post_views (post_id);

alter table public.post_views enable row level security;

create policy "post_views_select" on public.post_views
  for select using (true);

create policy "post_views_insert" on public.post_views
  for insert with check (true);

create or replace view public.post_view_counts as
  select post_id, count(*)::integer as view_count
  from public.post_views
  group by post_id;